<?php
// $Id: token.install,v 1.1.2.3 2008/06/28 15:09:32 greggles Exp $

/**
 * @file
 * The install and update code for the token module.
 *
 * @ingroup token
 */

function token_install() {
  db_query("UPDATE {system} SET weight = 10 WHERE name = 'token'");
}

function token_update_1() {
  $ret = array();
  $ret[] = update_sql("UPDATE {system} SET weight = 10 WHERE name = 'token'");
  return $ret;
}