<?php
// $Id: artmob_usage_request_ticket.module,v 1.0 2008/03/01 08:31:22 stop14 Exp $

/**
 * @file
 * A helper module for Artmob Respond.  Allows users to submit a request to use site content.
 */


//* Implementation of hook_node_info().

function artmob_usage_request_ticket_node_info() {
  return array(
    'am_usage_request_ticket' => array(
      'name' => t('Usage Request Ticket'),
      'module' => 'artmob_usage_request_ticket',
      'description' => t("This allows a user to enter a new usage request ticket")
    ),
  );
}

// Implementation of hook_access().

function artmob_usage_request_ticket_access($op, $node) {
  if ($op == 'create') {
    return user_access('Add Response Tickets');
  }
  else if ($op == 'update') {
    return user_access('Edit Response Tickets');
  }
  else if ($op == 'delete') {
    return user_access('Remove Response Tickets');
  }
  else if ($op == 'view') {
    $access = user_access('View Response Tickets');
    if ( $node->is_public == 0 ) {
      $access = $access and user_access('View Private Response Tickets');
    }
    return $access;
  }
  else {
    return FALSE;
  }
}

/**
 * Implementation of hook_link().
*/

/**
 * Implementation of hook_menu().
 */
function artmob_usage_request_ticket_menu($may_cache) {
  $items = array();

  if ($may_cache) {
  }
  else {
  }

  return $items;
}


function artmob_usage_request_ticket_view($node, $teaser = FALSE, $page = FALSE) {
  if ($teaser) {
    $node->teaser = check_markup($node->teaser, $node->format, FALSE);
    $node->content['artmob_usage_request_ticket'] = array('#value' => theme( 'artmob_usage_request_ticket_teaser', $node, $page ));
  }

  if ($page) {
    $node->body = check_markup($node->body, $node->format, FALSE);
    $node->content['artmob_usage_request_ticket'] = array('#value' => theme( 'artmob_usage_request_ticket_page', $node, $page ));
  }
  return $node;

}

function theme_artmob_usage_request_ticket_teaser( $node, $page ) {
  $content = '';
  $content .= $node->teaser;
  return $content;
}

function theme_artmob_usage_request_ticket_page( $node, $page ) {
  $content = '';
  $content .= $node->body;
  return $content;
}

/**
 * Implementation of hook_block().
 *
 * Displays the Link in a block.
 */
function artmob_usage_request_ticket_block($op = 'list', $delta = 0) {
  //Possible choices for $op are: list,configure,save & view
  //if $op is list then must return an array of arrays which must at least
  //define an 'info' element describing the block.  Other optional elements include
  //weight, enabled and region (ie 'right' or 'left).
  
  //if $op is view then we must return an array which must have a 'subject'
  //element and a 'content' element defining the block (indexed by $delta).
  
  //if $op is configure then optionally return a string containing the
  //configuration form.
  
  //if $op is save then return nothing.
  
  if ($op == 'list') {
//    $block[0]['info'] = t('Articles contributed by...');
//    $block[1]['info'] = t('licenses to this item...');
    return $block;
  }
  else if ($op == 'configure') {
    switch ($delta) {
      case 0:
        break;
    }
    return $form;
  }
  else if ($op == 'save') {
    switch ($delta) {
      case 0:
        break;
    }
  }
  else if ($op == 'view') {
    switch ($delta) {
      /*
      case 0: //Articles contributed by...
        if ( (arg(0) == 'node') and (is_numeric(arg(1)))) {
          $nid = arg(1);
          $node = node_load( $nid );
          if ( $node->type = 'license' ) {
            $ContentArray = array();
            $ContentArray = license_ArticlesFromThislicense( $nid );
            $block['subject'] = 'license';
            $block['content'] = theme('license_articles_by_block',$ContentArray);
          }
        }
        break;
      case 1: //licenses to this item...
        if ( (arg(0) == 'node') and (is_numeric(arg(1)))) {
          $nid = arg(1);
          $node = node_load( $nid );
          if ( $node->type = 'Artcles' ) {
            $ContentArray = array();
            $ContentArray = license_licensesFromThisArticle( $nid );
            $block['subject'] = 'license';
            $block['content'] = theme('license_contributed_by_block',$ContentArray );
          }
        }
        break;
        */
    }
  }
} 

// Implementation of hook_insert().

function artmob_usage_request_ticket_insert($node) {
  $node->ticket_number = db_next_id('am_ticketid');
  db_query("INSERT INTO {am_usage_request_ticket} (nid, uid, ticket_number, ticket_link_nid,
                                               is_public, ticket_name, ticket_email, ticket_status,
                                               dispute_status)
                               VALUES (%d, %d, %d, %d, %d, '%s', '%s', '%s', '%s' )",
       $node->nid, $node->uid, $node->ticket_number, $node->ticket_link_nid,
       $node->is_public, $node->ticket_name, $node->ticket_email, $node->ticket_status,
       $node->dispute_status);
}

// Implementation of hook_update().
function artmob_usage_request_ticket_update($node) {
  db_query("UPDATE {am_usage_request_ticket}
            set uid = %d,
            ticket_number = %d,
            ticket_link_nid = %d,
            is_public = %d,
            ticket_name = '%s',
            ticket_email = '%s',
            ticket_status = '%s',
            dispute_status = '%s'
            
            where nid = %d",

            $node->uid,
            $node->ticket_number,
            $node->ticket_link_nid,
            $node->is_public,
            $node->ticket_name,
            $node->ticket_email,
            $node->ticket_status,
            $node->dispute_status,

            $node->nid);
}  

// Implementation of hook_delete().
function artmob_usage_request_ticket_delete($node) {
  db_query("delete FROM {am_usage_request_ticket}
             where nid = %d",
             $node->nid);
}


// Implementation of hook_load().
function artmob_usage_request_ticket_load($node) {

/* joe's code
  $t = db_fetch_object(db_query('SELECT * FROM {am_license} WHERE nid = %d', $node->nid));
  return $t;
*/

  $t = db_fetch_array(db_query('SELECT * FROM {am_usage_request_ticket} WHERE nid = %d', $node->nid));
  return $t;
}


/**
 * Implementation of hook_submit().
 */
function artmob_usage_request_ticket_submit($node) {
  global $user;
  // Set default values for non-administrators.
  if (!user_access('administer nodes')) {
    $node->revision = 1;
    $node->uid = $user->uid;
  }
}


// Implementation of hook_form().
function artmob_usage_request_ticket_form($node) {

  $form['usage_request_ticket'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('licensing ticket'),
    '#weight'        => -5,
    '#collapsible'   => TRUE,
    '#collapsed'     => FALSE
  );

  $form['usage_request_ticket']['ticket_number'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Ticket #'),
    '#default_value' => $node->ticket_number,
    '#tree'          => 'FALSE',
    '#rows'          => 1,
    '#required'      => TRUE,
    '#disabled'        => True,
  );

  $form['usage_request_ticket']['title'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Subject'),
    '#default_value' => $node->title,
    '#description'   => t("enter the subject"),
    '#tree'          => 'FALSE',
    '#rows'          => 1,
    '#required'      => TRUE
  );

  $form['usage_request_ticket']['body'] = array(
    '#type'          => 'textarea',
    '#title'         => t('Comment'),
    '#default_value' => $node->body,
    '#description'   => t("enter your comment"),
    '#tree'          => 'FALSE',
    '#rows'          => 3,
    '#required'      => TRUE
  );
  $form['usage_request_ticket']['format'] = filter_form($node->format);

  if ( $node->uid == 0 ) {
    $site_user_name = 'N/A';
  } 
  else {
    $site_user = db_fetch_object(db_query('SELECT * FROM {users} WHERE uid = %d', $node->uid));
    $site_user_name = $site_user->name;
  }

  $form['usage_request_ticket']['uid'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Site User Name'),
    '#default_value' => $site_user_name,
    '#description'   => t("Name of user (if logged in)"),
    '#tree'          => 'FALSE',
    '#rows'          => 0,
    '#disabled'        => True,
  );

  $form['usage_request_ticket']['ticket_name'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Name'),
    '#default_value' => $node->ticket_name,
    '#description'   => t("Name of user (if not logged in)"),
    '#tree'          => 'FALSE',
    '#rows'          => 0,
    '#disabled'        => True,
  );

  $form['usage_request_ticket']['ticket_email'] = array(
    '#type'          => 'textfield',
    '#title'         => t('email'),
    '#default_value' => $node->ticket_email,
    '#description'   => t("Email of user (if not logged in)"),
    '#tree'          => 'FALSE',
    '#rows'          => 1,
    '#disabled'        => True,
  );
  
  $form['usage_request_ticket']['is_public'] = array(
    '#type' => 'checkbox',
    '#title' => t("Make my comments public"),
    '#default_value' => $node->is_public,
    '#weight' => 0,
  );

  $form['usage_request_ticket']['ticket_link_nid'] = array(
    '#type'          => 'textfield',
    '#title'         => t('linked node id'),
    '#default_value' => $node->ticket_link_nid,
    '#tree'          => 'FALSE',
    '#rows'          => 1,
    '#disabled'      => True,
  );
  
  $form['usage_request_ticket']['ticket_status'] = array(
      '#type'     => 'select',
      '#title'    => 'Ticket Status',
      '#options'    => artmob_respond_get_ticket_status_list(),
      '#default_value' => $node->ticket_status
  );

  $form['usage_request_ticket']['dispute_status'] = array(
      '#type'     => 'select',
      '#title'    => 'Dispute Status',
      '#options'    => artmob_respond_get_dispute_status_list(),
      '#default_value' => $node->dispute_status
  );

  return $form;

}

/**
 * Implementation of hook_form_alter().
 *
*/
function artmob_usage_request_ticket_form_alter($form_id, &$form) {
  // boilerplate code to determine the node type of the form
  if (isset($form['type'])) {
    $type = $form['type']['#value'];
  }
  elseif (isset($form['orig_type'])) {
      $type = $form['orig_type']['#value'];
  } 
  else {
    return;
  }

  switch ($form_id) {
    // Form addition that appears on Content Types page. Drupal saves as a setting.
    case 'node_type_form':
      break;

    // Form addition to all Enabled node types.  A node is enabled using
    // rdolicense radio button that we added to the content types page
    // in the hook_form_alter hook above.
    case $type .'_node_form':
      break;
  }
}


/**
 * Implementation of hook_nodeapi().
 *
 */
function artmob_usage_request_ticket_nodeapi($node, $op, $teaser, $page) {
  switch ($op) {
    case 'submit':
      break;
    case 'update':
      $bupdate = TRUE;

      //Fall through, with flag.  Therefore with every update we delete
      //the old associated records and then resave the new ones

    case 'delete':

      if (!$bupdate) {
        break;
      }

    case 'insert':
      break;
    case 'load':
      break;
    case 'prepare':
      break;
    case 'view':
      break;
    case 'update':
      break;
    case 'delete revision':
      break;
    case 'submit':
      break;
  }
}


// Implementation of hook_help().
function artmob_usage_request_ticket_help($section) {
  switch ($section) {
    case 'admin/help#description':
      return t('Enables the creation of usage request tickets.');
      break;
    case 'admin/modules#description':
      return t('Enables the creation of usage request tickets.');
      break;
    case 'admin/node/add#artmob_usage_request_ticket':
      return t('A usage request ticket. Use this page to add a usage request ticket.');
      break;
  }
}


